# Generated by Django 3.0.6 on 2020-07-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0003_auto_20200714_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='description',
            field=models.CharField(blank=None, default='', max_length=511),
        ),
    ]
