# Generated by Django 3.0.6 on 2020-07-18 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0004_destination_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='stop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trip.Stop'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='start_time',
            field=models.TimeField(blank=None),
        ),
        migrations.AlterField(
            model_name='destination',
            name='stop_time',
            field=models.TimeField(blank=None),
        ),
        migrations.AlterField(
            model_name='trip',
            name='accessability',
            field=models.CharField(choices=[('High Accessible', 'High Accessible'), ('Medium Accessible', 'Medium Accessible'), ('Low Accessible', 'Low Accessible')], default='HIGH', max_length=63),
        ),
        migrations.AlterUniqueTogether(
            name='destination',
            unique_together={('trip', 'name')},
        ),
        migrations.RemoveField(
            model_name='destination',
            name='stop_list',
        ),
    ]
