# Generated by Django 3.0.6 on 2020-07-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0005_auto_20200718_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stop',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='trip/images'),
        ),
    ]
