# Generated by Django 3.0.6 on 2020-07-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0007_tripcollaborator'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
