# Generated by Django 3.0.6 on 2020-07-11 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('execution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warning',
            name='level',
            field=models.CharField(choices=[('HIGH', 'HIGH'), ('MEDIUM', 'MEDIUM'), ('LOW', 'LOW'), ('INFO', 'INFO')], default='INFO', max_length=63),
        ),
        migrations.AddField(
            model_name='warning',
            name='radius',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='WarningAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(default='Ignore', max_length=63)),
                ('action', models.CharField(default='ignore', max_length=63)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('warning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='execution.Warning')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
