# Generated by Django 3.0.6 on 2020-07-14 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0002_auto_20200711_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warningaction',
            name='warning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warning_action', to='execution.Warning'),
        ),
    ]
