# Generated by Django 3.0.6 on 2020-07-19 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0003_auto_20200714_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='warning',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='warning',
            name='snooze_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='warning',
            name='level',
            field=models.CharField(choices=[(4, 'HIGH'), (3, 'MEDIUM'), (2, 'LOW'), (1, 'INFO')], default='INFO', max_length=63),
        ),
    ]
